language: node_js
node_js:
- node
install:
- yarn install
- cd client/ && yarn install && cd ../
script:
- cd client/ && yarn build
deploy:
  provider: heroku
  api_key:
    secure: Tus653PEIvaRXMmaP6yPbvK4DLAkWTp83e1jV0vN3sypGWrgCvIviyzhF81dGFDFJF9VAxQBm8DxCyEpNaKlAVjmnIZddSXftp/KOy80gdcxXAB6nJsfv4MCoAfLVi+WuPR+7uaja8nEdxFu6ml73Ej1HYT3uhcL/9tJIDrdQuaQOToOttvauOKkWZ1EuRX0+aXjVrZPn2KhppdoDtyxKkRk81ss09D6usv4aBOzVtC13EiVtbCi+1rcofCbSS7BlNa7JdcgMx4LERpqx3WGI/YutavCzKpqIH+fzkRTcvGwW5oQJvH3mhq+nWMp6WbWzaGT+cj+ypbPmnCWkhKyHNnZYejZDlSqiCYFQOY0STfQJyN/Hx/OjDay4H1wf0WaBalb+xTGHe96cJb6l6/PF1hdhefA3O2rlWwenQ3lwkrffpjSBbBzi/LCMCdSKo/1qTBUtQdhbjbJrqyzxjcSvznBw6PCDHKirr+aHkptQbqtXLvm8fSoPXJtd60uACHrw/jZFzrRDiDL1WSn6hvic+kti1YtSDbXB/32jztdKUJ+P/KBP8JE9qVU5JVCdWqUcF9SZZhh8pIqdYSTNrdWM31ssUeDQFTgD1LIJyiRvODJMX4w5RX/oHpotaLbwnuXZUSRcTQVTpHthwRVosCeWmK+HeKXRWGq/p27XFVACNw=
  app: openfinances
  on: master
